### ISSUE TITLE
Show min/max

### ISSUE THREAD

**Issue by Milde87** [tpartner/LimeSurvey-Range-Slider-4x-5x#1]
Hey,

thank you for the great template for a range slider. However, I have some problems with it. In the custom settings, I cannot see the "Show min/max" option (see attached file). Furthermore, the suffix or prefix of the tooltips is not displayed, although I entered a symbol. Do you have an idea what this is?

Thanks a lot.
Michael
![Slider](https://user-images.githubusercontent.com/45991141/115355848-5ca1dc80-a1bb-11eb-8eab-b5a9a0066a54.PNG)

**Comment by tpartner** [comment]
What LS version? Are there any JavaScript errors in the browser console? 

This is what I see in version 4.5.1 .
![capture_2](https://user-images.githubusercontent.com/1437729/115383734-345ab380-a1a4-11eb-94d7-bbb88eb44951.png)

Try this sample survey (remove the .txt extension before importing):
[limesurvey_survey_858878.lss.txt](https://github.com/tpartner/LimeSurvey-Range-Slider-4x/files/6342874/limesurvey_survey_858878.lss.txt)

**Comment by Milde87** [comment]
I have version Version 4.3.19+201005. Yes, there is indeed a mistake (see below). Then I will have to update LimeSurvey, won't I?
![js_error](https://user-images.githubusercontent.com/45991141/115384565-7c46fe00-a1d7-11eb-8805-7a336aa33b03.PNG)

**Comment by tpartner** [comment]
Yes, please update to the latest version and retest. Many question theme bugs have been addressed in the newer versions.

**Comment by Milde87** [comment]
Ok, thanks. Now it works with version 4.5.1.
